FROM python:3.11-slim-bullseye

# Set utility env varibles
ENV PATH=/generated_text_detector/miniconda/bin:$PATH

# Set workdir
WORKDIR /generated_text_detector

# Install python requirements
COPY generated_text_detector/requirements.txt .
RUN pip3 install -r requirements.txt --no-cache
RUN python -m nltk.downloader punkt

# Copy code to container
COPY generated_text_detector/ generated_text_detector/
COPY etc/ etc/
COPY key.pem cert.pem ./
COPY version.txt ./

EXPOSE 8080
CMD uvicorn --host 0.0.0.0 --port 8080 --ssl-keyfile=./key.pem --ssl-certfile=./cert.pem generated_text_detector.fastapi_app:app
